Gabriel Click Nerd (Super Mario)
mindera-school/MS5-Basic-App-Exercises pull request #3
Opened 2023-02-13 15:05 UTC by Gabriel-Sous-a

2023-02-14 18:10 UTC, 201flaviosilva commented
Antes de ver qualquer coisa, confirma se as imagens e as fonts não tem direitos de autor! Na pior das hipóteses faz um webgrafia!

2023-02-20 15:46 UTC, 201flaviosilva requested changes
Para além dos comentários, verifica se podes usar as imagens no projeto e elimina as que não estas a usar

2023-02-20 15:46 UTC, 201flaviosilva commented on src/scrypt.js
> +
Formata o código

2023-02-20 15:46 UTC, 201flaviosilva commented on src/scrypt.js
> +});
Tenho a certeza que consegues reduzir este código para uma função só

2023-02-20 15:46 UTC, 201flaviosilva commented on src/scrypt.js
> +  }
Podias ter reduzido este código assim:

```suggestion
  const trans = {
    en: "this doesn't really work in english.",
    pt: "Mario? Aquele que te comeu atras do armario.",
    cn: "读白 不要忘记 不要错过 记得去电影院看《速度与激情9 因为非常好电影 动作非常好 差不多一样冰淇淋 再见",
  }
  const langQuote = document.getElementById("langQuote");
  langQuote.innerHTML = trans[lang];
```

2023-02-20 15:46 UTC, 201flaviosilva commented on src/scrypt.js
> +});
Este tipo de animações são normalmente feitas em CSS, há alguma razão para a teres feita em JS?

2023-02-20 15:46 UTC, 201flaviosilva commented on src/scrypt.js
> +});
Idealmente, isto deveria ser feito com class em CSS. Mas para além disso podias reduzir imenso este código usando apenas uma função

2023-02-20 15:46 UTC, 201flaviosilva commented on src/style2.scss
> +body {
Sabes o que eu acho do nome deste ficheiro?

(E é que ainda por cima não há o `style1.scss`)

2023-02-20 15:46 UTC, 201flaviosilva commented on src/style2.scss
> +  justify-content: center;;
```suggestion
  justify-content: center;
```

2023-02-20 15:46 UTC, 201flaviosilva commented on src/style2.scss
> +  }
https://sass-lang.com/documentation/at-rules/mixin

2023-02-20 15:46 UTC, 201flaviosilva commented on src/style2.scss
> +  flex-direction: row;
Não precisas disto, por padrão o `flex` já é em `row`

2023-02-20 15:46 UTC, 201flaviosilva commented on src/styles.css
> +body {
O nome do output do SCSS deve sempre ter o mesmo nome do ficheiro original

2023-02-20 15:46 UTC, 201flaviosilva commented on index.html
> +      <img src="images/adds/giphy3.webp" alt="" class="addImages" />
Nenhuma imagem tem o atributo `alt` bem definido

2023-02-20 15:46 UTC, 201flaviosilva commented on index.html
> +      <div id="langQuote">Mario? Aquele que te comeu atras do armario</div>
Se isto é apenas um elemento de texto deve ser usado com uma tag de texto, como um `p` ou um `span`

2023-02-20 15:46 UTC, 201flaviosilva commented on README.md
> -# MS5-Basic-App-Exercises
Verifica aqui a tua versão renderizada:
https://github.com/mindera-school/MS5-Basic-App-Exercises/blob/a61dfc0788a9207040b1565804e377c9f1ff7758/README.md

Imagino que não seja parecido ao que pensavas :)

Dá uma vista de olhos nisto: https://www.markdownguide.org/cheat-sheet/

2023-03-13 11:03 UTC, 201flaviosilva commented on src/scrypt.js
> +});*/
Código comentado?

2023-03-13 11:03 UTC, 201flaviosilva commented on src/styles.scss
> +  background-image: url("/images/background.jpg");
```suggestion
  background-image: url("./images/background.jpg");
```

2023-03-13 11:03 UTC, 201flaviosilva commented on src/styles.scss
> +  src: url("/font/SuperMario256.ttf");
```suggestion
  src: url("./font/SuperMario256.ttf");
```

2023-04-20 16:14 UTC, 201flaviosilva approved these changes

2023-04-20 16:14 UTC, 201flaviosilva commented on src/scrypt.js
`scrypt.js`?

2023-04-20 16:27 UTC, Adan0k approved these changes
nice script!

2024-02-16 15:57 UTC, merged